# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: nuget
    directory: /EpubReader
    schedule:
      interval: daily
    ignore:
        - dependency-name: "Microsoft.Maui.Controls"
        - dependency-name: "Microsoft.Maui.Core"
        - dependency-name: "CommunityToolkit.Maui"
        - dependency-name: "CommunityToolkit.Maui.Core"
        - dependency-name: "CommunityToolkit.Mvvm"
        - dependency-name: "HtmlAgilityPack"
        - dependency-name: "Microsoft.Maui.Graphics"
        - dependency-name: "Microsoft.Maui.Graphics.Skia"
        - dependency-name: "Microsoft.Extensions.Logging.Debug"
        - dependency-name: "MetroLog.Maui"
        - dependency-name: "FFImageLoading.Maui"
        - dependency-name: "SixLabors.ImageSharp"
        - dependency-name: "VersOne.Epub"
        - dependency-name: "Syncfusion.Maui.Toolkit"
        - dependency-name: "System.ServiceModel.Syndication"
        - dependency-name: "sqlite-net-pcl"
        - dependency-name: "SQLitePCLRaw.bundle_green"
        - dependency-name: "SQLite.Net.Extensions"
         
