version: 2
registries:
  custom-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
- package-ecosystem: nuget
  directory: "/"
  registries:
    - custom-nuget
  schedule:
    interval: daily
    ignore:
        - dependency-name: "Microsoft.Maui.Controls"
        - dependency-name: "Microsoft.Maui.Core"
        - dependency-name: "MicrosoftMauiGraphicsVersion"         # maestro
        - dependency-name: "Microsoft.Maui.Graphics*"             # maestro
        - dependency-name: "SkiaSharp*"                           # needs to be done manually with maui graphics
        - dependency-name: "HarfBuzzSharp*"                       # needs to be done manually with maui graphics
        - dependency-name: "Newtonsoft.Json"                      # needs to be done manually to match VS
