version: 2
updates:
  - package-ecosystem: nuget
    directory: /EpubReader
    schedule:
      interval: daily
    ignore:
         - dependency-name: "Microsoft.Maui.Controls"
         - dependency-name: "Microsoft.Maui.Core"
         - dependency-name: "Microsoft.Maui.Essentials"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
